### ISSUE TITLE
Building error Ubuntu20.04 and ros foxy

### ISSUE THREAD

**Issue by dsponer** [RobotecAI/ros2cs#50]
Hello
I have a problem with build my ros2cs
The error crashed all process then I build tests

The type or namespace name 'example_interfaces

**Comment by Deric-W** [comment]
Hello,
can you please show us the full error?

**Comment by dsponer** [comment]
This is full error

ros2cs_performance_listener_dotnetcore -> /home/ubuntu/ros2cs/build/ros2cs_examples/Release/netcoreapp6.0/ros2cs_performance_listener.dll
/home/ubuntu/ros2cs/src/ros2cs/ros2cs_examples/ROS2Service.cs(39,77): error CS0246: The type or namespace name 'example_interfaces' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/ros2cs/build/ros2cs_examples/ros2cs_service/ros2cs_service_dotnetcore.csproj]
/home/ubuntu/ros2cs/src/ros2cs/ros2cs_examples/ROS2Service.cs(39,19): error CS0246: The type or namespace name 'example_interfaces' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/ros2cs/build/ros2cs_examples/ros2cs_service/ros2cs_service_dotnetcore.csproj]
/home/ubuntu/ros2cs/src/ros2cs/ros2cs_examples/ROS2Service.cs(25,28): error CS0246: The type or namespace name 'example_interfaces' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/ros2cs/build/ros2cs_examples/ros2cs_service/ros2cs_service_dotnetcore.csproj]
/home/ubuntu/ros2cs/src/ros2cs/ros2cs_examples/ROS2Service.cs(25,71): error CS0246: The type or namespace name 'example_interfaces' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/ros2cs/build/ros2cs_examples/ros2cs_service/ros2cs_service_dotnetcore.csproj]

Build FAILED.

/home/ubuntu/ros2cs/src/ros2cs/ros2cs_examples/ROS2Service.cs(39,77): error CS0246: The type or namespace name 'example_interfaces' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/ros2cs/build/ros2cs_examples/ros2cs_service/ros2cs_service_dotnetcore.csproj]
/home/ubuntu/ros2cs/src/ros2cs/ros2cs_examples/ROS2Service.cs(39,19): error CS0246: The type or namespace name 'example_interfaces' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/ros2cs/build/ros2cs_examples/ros2cs_service/ros2cs_service_dotnetcore.csproj]
/home/ubuntu/ros2cs/src/ros2cs/ros2cs_examples/ROS2Service.cs(25,28): error CS0246: The type or namespace name 'example_interfaces' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/ros2cs/build/ros2cs_examples/ros2cs_service/ros2cs_service_dotnetcore.csproj]
/home/ubuntu/ros2cs/src/ros2cs/ros2cs_examples/ROS2Service.cs(25,71): error CS0246: The type or namespace name 'example_interfaces' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/ros2cs/build/ros2cs_examples/ros2cs_service/ros2cs_service_dotnetcore.csproj]
    0 Warning(s)
    4 Error(s)

**Comment by Deric-W** [comment]
Did you execute `./get_repos.sh`?
Try to clear the CMake cache.

**Comment by adamdbrw** [comment]
@dsponer was your issue resolved?

**Comment by dsponer** [comment]
@adamdbrw, Yes, I solved the problem

I did the following
1) Removed my ROS2
2) Installed ros-foxy-base
3) I downloaded the package from the foxy_fixes_for_custom_messages branch
These steps allowed me to solve the problem
Thank you for your help
